// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: query.proto

package sc2proto

import (
	"reflect"
	"sync"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pathing                    []*RequestQueryPathing            `protobuf:"bytes,1,rep,name=pathing" json:"pathing,omitempty"`
	Abilities                  []*RequestQueryAvailableAbilities `protobuf:"bytes,2,rep,name=abilities" json:"abilities,omitempty"`
	Placements                 []*RequestQueryBuildingPlacement  `protobuf:"bytes,3,rep,name=placements" json:"placements,omitempty"`
	IgnoreResourceRequirements *bool                             `protobuf:"varint,4,opt,name=ignore_resource_requirements,json=ignoreResourceRequirements" json:"ignore_resource_requirements,omitempty"` // Ignores requirements like food, minerals and so on.
}

func (x *RequestQuery) Reset() {
	*x = RequestQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQuery) ProtoMessage() {}

func (x *RequestQuery) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQuery.ProtoReflect.Descriptor instead.
func (*RequestQuery) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *RequestQuery) GetPathing() []*RequestQueryPathing {
	if x != nil {
		return x.Pathing
	}
	return nil
}

func (x *RequestQuery) GetAbilities() []*RequestQueryAvailableAbilities {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *RequestQuery) GetPlacements() []*RequestQueryBuildingPlacement {
	if x != nil {
		return x.Placements
	}
	return nil
}

func (x *RequestQuery) GetIgnoreResourceRequirements() bool {
	if x != nil && x.IgnoreResourceRequirements != nil {
		return *x.IgnoreResourceRequirements
	}
	return false
}

type ResponseQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pathing    []*ResponseQueryPathing            `protobuf:"bytes,1,rep,name=pathing" json:"pathing,omitempty"`
	Abilities  []*ResponseQueryAvailableAbilities `protobuf:"bytes,2,rep,name=abilities" json:"abilities,omitempty"`
	Placements []*ResponseQueryBuildingPlacement  `protobuf:"bytes,3,rep,name=placements" json:"placements,omitempty"`
}

func (x *ResponseQuery) Reset() {
	*x = ResponseQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseQuery) ProtoMessage() {}

func (x *ResponseQuery) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseQuery.ProtoReflect.Descriptor instead.
func (*ResponseQuery) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseQuery) GetPathing() []*ResponseQueryPathing {
	if x != nil {
		return x.Pathing
	}
	return nil
}

func (x *ResponseQuery) GetAbilities() []*ResponseQueryAvailableAbilities {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *ResponseQuery) GetPlacements() []*ResponseQueryBuildingPlacement {
	if x != nil {
		return x.Placements
	}
	return nil
}

//--------------------------------------------------------------------------------------------------
type RequestQueryPathing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Start:
	//	*RequestQueryPathing_StartPos
	//	*RequestQueryPathing_UnitTag
	Start  isRequestQueryPathing_Start `protobuf_oneof:"start"`
	EndPos *Point2D                    `protobuf:"bytes,3,opt,name=end_pos,json=endPos" json:"end_pos,omitempty"`
}

func (x *RequestQueryPathing) Reset() {
	*x = RequestQueryPathing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestQueryPathing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryPathing) ProtoMessage() {}

func (x *RequestQueryPathing) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQueryPathing.ProtoReflect.Descriptor instead.
func (*RequestQueryPathing) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (m *RequestQueryPathing) GetStart() isRequestQueryPathing_Start {
	if m != nil {
		return m.Start
	}
	return nil
}

func (x *RequestQueryPathing) GetStartPos() *Point2D {
	if x, ok := x.GetStart().(*RequestQueryPathing_StartPos); ok {
		return x.StartPos
	}
	return nil
}

func (x *RequestQueryPathing) GetUnitTag() uint64 {
	if x, ok := x.GetStart().(*RequestQueryPathing_UnitTag); ok {
		return x.UnitTag
	}
	return 0
}

func (x *RequestQueryPathing) GetEndPos() *Point2D {
	if x != nil {
		return x.EndPos
	}
	return nil
}

type isRequestQueryPathing_Start interface {
	isRequestQueryPathing_Start()
}

type RequestQueryPathing_StartPos struct {
	StartPos *Point2D `protobuf:"bytes,1,opt,name=start_pos,json=startPos,oneof"`
}

type RequestQueryPathing_UnitTag struct {
	UnitTag uint64 `protobuf:"varint,2,opt,name=unit_tag,json=unitTag,oneof"`
}

func (*RequestQueryPathing_StartPos) isRequestQueryPathing_Start() {}

func (*RequestQueryPathing_UnitTag) isRequestQueryPathing_Start() {}

type ResponseQueryPathing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distance *float32 `protobuf:"fixed32,1,opt,name=distance" json:"distance,omitempty"` // 0 if no path exists
}

func (x *ResponseQueryPathing) Reset() {
	*x = ResponseQueryPathing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseQueryPathing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseQueryPathing) ProtoMessage() {}

func (x *ResponseQueryPathing) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseQueryPathing.ProtoReflect.Descriptor instead.
func (*ResponseQueryPathing) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseQueryPathing) GetDistance() float32 {
	if x != nil && x.Distance != nil {
		return *x.Distance
	}
	return 0
}

//--------------------------------------------------------------------------------------------------
type RequestQueryAvailableAbilities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitTag *uint64 `protobuf:"varint,1,opt,name=unit_tag,json=unitTag" json:"unit_tag,omitempty"`
}

func (x *RequestQueryAvailableAbilities) Reset() {
	*x = RequestQueryAvailableAbilities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestQueryAvailableAbilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryAvailableAbilities) ProtoMessage() {}

func (x *RequestQueryAvailableAbilities) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQueryAvailableAbilities.ProtoReflect.Descriptor instead.
func (*RequestQueryAvailableAbilities) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *RequestQueryAvailableAbilities) GetUnitTag() uint64 {
	if x != nil && x.UnitTag != nil {
		return *x.UnitTag
	}
	return 0
}

type ResponseQueryAvailableAbilities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Abilities  []*AvailableAbility `protobuf:"bytes,1,rep,name=abilities" json:"abilities,omitempty"`
	UnitTag    *uint64             `protobuf:"varint,2,opt,name=unit_tag,json=unitTag" json:"unit_tag,omitempty"`
	UnitTypeId *uint32             `protobuf:"varint,3,opt,name=unit_type_id,json=unitTypeId" json:"unit_type_id,omitempty"`
}

func (x *ResponseQueryAvailableAbilities) Reset() {
	*x = ResponseQueryAvailableAbilities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseQueryAvailableAbilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseQueryAvailableAbilities) ProtoMessage() {}

func (x *ResponseQueryAvailableAbilities) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseQueryAvailableAbilities.ProtoReflect.Descriptor instead.
func (*ResponseQueryAvailableAbilities) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseQueryAvailableAbilities) GetAbilities() []*AvailableAbility {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *ResponseQueryAvailableAbilities) GetUnitTag() uint64 {
	if x != nil && x.UnitTag != nil {
		return *x.UnitTag
	}
	return 0
}

func (x *ResponseQueryAvailableAbilities) GetUnitTypeId() uint32 {
	if x != nil && x.UnitTypeId != nil {
		return *x.UnitTypeId
	}
	return 0
}

//--------------------------------------------------------------------------------------------------
type RequestQueryBuildingPlacement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbilityId      *int32   `protobuf:"varint,1,opt,name=ability_id,json=abilityId" json:"ability_id,omitempty"`
	TargetPos      *Point2D `protobuf:"bytes,2,opt,name=target_pos,json=targetPos" json:"target_pos,omitempty"`
	PlacingUnitTag *uint64  `protobuf:"varint,3,opt,name=placing_unit_tag,json=placingUnitTag" json:"placing_unit_tag,omitempty"` // Not required
}

func (x *RequestQueryBuildingPlacement) Reset() {
	*x = RequestQueryBuildingPlacement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestQueryBuildingPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryBuildingPlacement) ProtoMessage() {}

func (x *RequestQueryBuildingPlacement) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQueryBuildingPlacement.ProtoReflect.Descriptor instead.
func (*RequestQueryBuildingPlacement) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{6}
}

func (x *RequestQueryBuildingPlacement) GetAbilityId() int32 {
	if x != nil && x.AbilityId != nil {
		return *x.AbilityId
	}
	return 0
}

func (x *RequestQueryBuildingPlacement) GetTargetPos() *Point2D {
	if x != nil {
		return x.TargetPos
	}
	return nil
}

func (x *RequestQueryBuildingPlacement) GetPlacingUnitTag() uint64 {
	if x != nil && x.PlacingUnitTag != nil {
		return *x.PlacingUnitTag
	}
	return 0
}

type ResponseQueryBuildingPlacement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *ActionResult `protobuf:"varint,1,opt,name=result,enum=sc2proto.ActionResult" json:"result,omitempty"`
}

func (x *ResponseQueryBuildingPlacement) Reset() {
	*x = ResponseQueryBuildingPlacement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseQueryBuildingPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseQueryBuildingPlacement) ProtoMessage() {}

func (x *ResponseQueryBuildingPlacement) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseQueryBuildingPlacement.ProtoReflect.Descriptor instead.
func (*ResponseQueryBuildingPlacement) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseQueryBuildingPlacement) GetResult() ActionResult {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ActionResult_Success
}

var File_query_proto protoreflect.FileDescriptor

var file_query_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73,
	0x63, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x9a, 0x02, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x37, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x63, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x52, 0x07, 0x70, 0x61, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x46, 0x0a, 0x09,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x73, 0x63, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x09, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x73, 0x63, 0x32, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x40, 0x0a,
	0x1c, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x1a, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0xdc, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x38, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x63, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x69,
	0x6e, 0x67, 0x52, 0x07, 0x70, 0x61, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x47, 0x0a, 0x09, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x73, 0x63, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x09, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x48, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x73, 0x63, 0x32, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x99,
	0x01, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50,
	0x61, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x30, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x63, 0x32, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x44, 0x48, 0x00, 0x52, 0x08,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x1b, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x74,
	0x5f, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x07, 0x75, 0x6e,
	0x69, 0x74, 0x54, 0x61, 0x67, 0x12, 0x2a, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x63, 0x32, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x44, 0x52, 0x06, 0x65, 0x6e, 0x64, 0x50, 0x6f,
	0x73, 0x42, 0x07, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x22, 0x32, 0x0a, 0x14, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x69,
	0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x3b,
	0x0a, 0x1e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x74, 0x54, 0x61, 0x67, 0x22, 0x98, 0x01, 0x0a, 0x1f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12,
	0x38, 0x0a, 0x09, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x63, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x09,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x6e, 0x69,
	0x74, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x75, 0x6e, 0x69,
	0x74, 0x54, 0x61, 0x67, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x22, 0x9a, 0x01, 0x0a, 0x1d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x63,
	0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x44, 0x52, 0x09,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x6c, 0x61,
	0x63, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x55, 0x6e, 0x69, 0x74,
	0x54, 0x61, 0x67, 0x22, 0x50, 0x0a, 0x1e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x63, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x6e, 0x77, 0x75, 0x7a, 0x68, 0x61, 0x6f, 0x2f, 0x73, 0x63,
	0x32, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x63, 0x32, 0x70, 0x72,
	0x6f, 0x74, 0x6f,
}

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData = file_query_proto_rawDesc
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_query_proto_rawDescData)
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_query_proto_goTypes = []interface{}{
	(*RequestQuery)(nil),                    // 0: sc2proto.RequestQuery
	(*ResponseQuery)(nil),                   // 1: sc2proto.ResponseQuery
	(*RequestQueryPathing)(nil),             // 2: sc2proto.RequestQueryPathing
	(*ResponseQueryPathing)(nil),            // 3: sc2proto.ResponseQueryPathing
	(*RequestQueryAvailableAbilities)(nil),  // 4: sc2proto.RequestQueryAvailableAbilities
	(*ResponseQueryAvailableAbilities)(nil), // 5: sc2proto.ResponseQueryAvailableAbilities
	(*RequestQueryBuildingPlacement)(nil),   // 6: sc2proto.RequestQueryBuildingPlacement
	(*ResponseQueryBuildingPlacement)(nil),  // 7: sc2proto.ResponseQueryBuildingPlacement
	(*Point2D)(nil),                         // 8: sc2proto.Point2D
	(*AvailableAbility)(nil),                // 9: sc2proto.AvailableAbility
	(ActionResult)(0),                       // 10: sc2proto.ActionResult
}
var file_query_proto_depIdxs = []int32{
	2,  // 0: sc2proto.RequestQuery.pathing:type_name -> sc2proto.RequestQueryPathing
	4,  // 1: sc2proto.RequestQuery.abilities:type_name -> sc2proto.RequestQueryAvailableAbilities
	6,  // 2: sc2proto.RequestQuery.placements:type_name -> sc2proto.RequestQueryBuildingPlacement
	3,  // 3: sc2proto.ResponseQuery.pathing:type_name -> sc2proto.ResponseQueryPathing
	5,  // 4: sc2proto.ResponseQuery.abilities:type_name -> sc2proto.ResponseQueryAvailableAbilities
	7,  // 5: sc2proto.ResponseQuery.placements:type_name -> sc2proto.ResponseQueryBuildingPlacement
	8,  // 6: sc2proto.RequestQueryPathing.start_pos:type_name -> sc2proto.Point2D
	8,  // 7: sc2proto.RequestQueryPathing.end_pos:type_name -> sc2proto.Point2D
	9,  // 8: sc2proto.ResponseQueryAvailableAbilities.abilities:type_name -> sc2proto.AvailableAbility
	8,  // 9: sc2proto.RequestQueryBuildingPlacement.target_pos:type_name -> sc2proto.Point2D
	10, // 10: sc2proto.ResponseQueryBuildingPlacement.result:type_name -> sc2proto.ActionResult
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	file_common_proto_init()
	file_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestQueryPathing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseQueryPathing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestQueryAvailableAbilities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseQueryAvailableAbilities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestQueryBuildingPlacement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseQueryBuildingPlacement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_query_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*RequestQueryPathing_StartPos)(nil),
		(*RequestQueryPathing_UnitTag)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_rawDesc = nil
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
